### ISSUE TITLE
Hotbars keep getting cleared.

### ISSUE THREAD

**Issue by intemptesta** [League-of-Foundry-Developers/foundry-token-hotbar#38] opened 2020-12-13 12:02 UTC
Foundry 0.7.7
DnD5e 1.1.1
Token Hotbar 4.2.0
Link to linked actor enabled.
Always link to actor enabled.
Shared Token Hotbar enabled.

After occupying the Hotbar page with macros, if I deselect the token or selecting other tokens sometimes all the macros on that page will be cleared. It's inconsistent on how it is happening, can be happened to both GM and Player side.

**Comment by janssen-io** [comment] 2020-12-14 12:44
Oof, that's not good. December is a busy month, but I'll have a look at it as soon as possible. 
Thanks for the report!

**Comment by EsotericOdyssey** [comment] 2021-02-01 20:44
I'm still having similar problems with this, players can't access hotbars I've set up for their tokens as GM, whenever they select a token I've set up with a hotbar it gets cleared.
Simple Worldbuilding 0.40
Token Hotbar 4.2.1
Always link to actor enabled.

**Comment by QuantumFunks** [comment] 2021-03-11 09:49
Im also having this issue. It a shame because i consider this one of the most useful modules and its unusable at the moment :(

**Comment by janssen-io** [comment] 2021-05-09 19:41
Unfortunately, I was not able to find a resolution to this anymore.

I had to change the `preUpdateUser` to `updateUser`, as preUpdateUser was no longer fired when the hotbar is updated. I'm 99% sure this is the cause of this issue.

For future reference, these two hooks were first one that fired under `preUpdateUser`:
https://github.com/janssen-io/foundry-token-hotbar/blob/c5003eb48291af0c375878f1ae43346b680b3d8b/src/main.ts#L85-L113

**Comment by janssen-io** [comment] 2021-11-06 11:51
Hi everyone, I'm currently working on a new version that's also compatible with the upcoming version of Foundry (v0.9.0). This issue will be fixed there as well. :)

**Closed** 2021-11-10 10:18 UTC
Labels: bug, fixed in beta
